#!/bin/bash

#title          :preinstall.sh
#description    :Preinstall Script for NoMAD wit LaunchAgent
#author         :Fabian Hartmann
#date           :2018-02-26
#version        :0.1
#usage          :./preinstall.sh
#notes          :
#bash_version   :
#============================================================================



#============================================================================
### Revision History:
##
##	Date	Version			Personnel			Notes
##	----	-------			----------------	-----
##	2018-02-26	0.1			Fabian Hartmann Script created
##
#============================================================================
#
SCRIPT_NAME=`basename "${0}"`
SCRIPT_PATH=`dirname "${0}"`
loggedInUser=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

su $loggedInUser -c "launchctl unload /Library/LaunchAgents/com.trusourcelabs.NoMAD.plist"

exit 0
