#!/bin/bash

#title          :postinstall.sh
#description    :Preinstall Script for ClickShareLauncher
#author         :Fabian Hartmann
#date           :2020-02-17
#version        :0.1
#usage          :./postinstall.sh
#notes          :
#bash_version   :
#============================================================================



#============================================================================
### Revision History:
##
##	Date	Version			Personnel			Notes
##	----	-------			----------------	-----
##	2020-02-17	0.1			Fabian Hartmann Script created
##
#============================================================================
#
SCRIPT_NAME=`basename "${0}"`
SCRIPT_PATH=`dirname "${0}"`
loggedInUser=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

su $loggedInUser -c "launchctl load /Library/LaunchAgents/com.barco.clicksharelauncher.plist"
